### DISCUSSION TITLE
theme assets folder during watch and production

### DISCUSSION THREAD

**Discussion by phoheisel** [gregsullivan/_tw#54] [Q&A] [answered]
During development, I link my assets at theme_name/theme/assets after running a bundle, those files will end up under theme_name/assets

Probably linking them like this is not the right way?

**Comment by gregsullivan** [comment]
Hi Philip—Thanks for posting this!

> During development, I link my assets at theme_name/theme/assets after running a bundle, those files will end up under theme_name/assets

That is definitely the expected outcome in terms of where the `assets` folder would end up after `npm run bundle`.

> Probably linking them like this is not the right way?

In what sense? Are the contents of the `assets` folder not meant to be part of the bundled theme (because they're used to generate other files, for example)?

Please let me know what kinds of files are inside the `assets` folder and why you're concerned about that folder being part of the published theme, and I'd be happy to give you feedback!

**Reply by phoheisel** [reply]
Yes, sorry for not asking more specificly.

Yes the assets should be and are in the bundle. I have fonts and images in that folder. My issue is linking them in my css files. As the link in dev and bundled production is not the same. Maybe I just missed how to dynamicly link them?

Example for my fonts.css:
`src: url('/wp-content/themes/theme_name/theme/assets/fonts/font-name.woff2')`

After bundling this link won't work as the fonts end up in /wp-content/themes/theme_name/assets/fonts/

**Reply by gregsullivan** [reply, marked as answer]
No problem at all! I understand now.

For fonts and images declared in CSS, I use relative links. Keeping in mind that the CSS all compiles into `./theme/style.css`, you can use something like `url('assets/fonts/font-name.woff2')`. Here's an example from a project I'm working on:

```css
@font-face {
	font-family: "Freight Sans Pro";
	src: url("fonts/freight-sans-pro-book.woff2") format("woff2"),
	     url("fonts/freight-sans-pro-book.woff") format("woff");
	font-weight: 400;
	font-style: normal;
}
```
